# Generated by Django 6.0.4 on 2026-04-25 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL adress (slug)')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='The name of the dish')),
                ('description', models.TextField(verbose_name='Description (composition, marinade)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (UAH)')),
                ('weight', models.IntegerField(help_text='Specify the weight of the portion', verbose_name='Weight (g/ml)')),
                ('image', models.ImageField(upload_to='dishes/', verbose_name='Photo')),
                ('is_available', models.BooleanField(default=True, verbose_name='It is available')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Spicy dish')),
                ('on_fire', models.BooleanField(default=True, verbose_name='Cooked on fire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
                'ordering': ['-created_at'],
            },
        ),
    ]
