# Generated by Django 6.0.4 on 2026-04-27 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('user_coords', models.TextField(blank=True, null=True, verbose_name='Координати (JSON)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Всього (₴)')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Доставка (₴)')),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Відстань (км)')),
                ('status', models.CharField(choices=[('RC', 'Отримано'), ('PR', 'Готується'), ('OD', 'В дорозі'), ('CO', 'Виконано')], default='RC', max_length=2, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='is_spicy',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL адреса (slug)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наявності'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='on_fire',
            field=models.BooleanField(default=False, verbose_name='🔥 SMOKY CHOICE'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна (₴)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва страви'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.IntegerField(verbose_name='Вага (г)'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.order')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції',
            },
        ),
    ]
